// ============================================================
// VIRAL CONTENT DATABASE — High-quality simulated TikTok/IG content
// Images: Unsplash (real portrait/lifestyle photos)
// Videos: Pexels portrait (9:16) matching each style
// 100+ entries across 4 content types
// ============================================================

const U = (id) => `https://images.unsplash.com/photo-${id}?w=630&h=1120&fit=crop`;

const PEXELS_VIDEOS = [
  "https://videos.pexels.com/video-files/5971265/5971265-sd_506_960_25fps.mp4",
  "https://videos.pexels.com/video-files/6595457/6595457-sd_360_640_30fps.mp4",
  "https://videos.pexels.com/video-files/6775037/6775037-sd_540_960_30fps.mp4",
  "https://videos.pexels.com/video-files/8135599/8135599-sd_540_960_25fps.mp4",
  "https://videos.pexels.com/video-files/7677557/7677557-sd_360_640_25fps.mp4",
  "https://videos.pexels.com/video-files/5532769/5532769-sd_360_640_25fps.mp4",
  "https://videos.pexels.com/video-files/4057605/4057605-sd_540_960_25fps.mp4",
  "https://videos.pexels.com/video-files/3205920/3205920-sd_506_960_25fps.mp4",
];

const V = (i) => PEXELS_VIDEOS[i % PEXELS_VIDEOS.length];

export const VIRAL_CONTENT = [
  // ====================  SLIDESHOW (1–32)  ====================
  {
    id: 1,
    caption: "Weird manager rules that made my team the top performers",
    subCaption: "(yes, your team will literally kiss you for these)",
    contentType: "slideshow",
    tags: ["B2B App", "B2B SaaS/Platform"],
    num_likes: 10100,
    num_views: 223000,
    videoUrl: V(0),
    thumbnail: U("1556761175-5973dc0f32e7"),
    slides: [
      { imageUrl: U("1460925895917-afdab827c52f"), text: "Rule #1: No meetings on Mondays. Period." },
      { imageUrl: U("1551434678-e076c223a692"), text: "Rule #2: Everyone gets a 'CEO day' once a month to work on whatever they want" },
      { imageUrl: U("1553877522-43269d4ea984"), text: "Rule #3: If it can be a Slack message, it should NEVER be a meeting" },
      { imageUrl: U("1522071820081-009f0129c71c"), text: "Rule #4: Public praise, private feedback. Always." },
      { imageUrl: U("1556761175-5973dc0f32e7"), text: "Rule #5: I give my team permission to say NO to me" },
    ],
  },
  {
    id: 2,
    caption: "7 Things Every Man Should Start Doing to Raise His Vibration",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Self Improvement", "Personal Brand"],
    num_likes: 9200,
    num_views: 103500,
    videoUrl: V(1),
    thumbnail: U("1507003211169-0a1dd7228f2d"),
    slides: [
      { imageUrl: U("1493770348161-369560ae357d"), text: "1. Wake up before 6am — own the morning, own the day" },
      { imageUrl: U("1571019613454-1cb2f99b2d8b"), text: "2. Cold exposure daily — it rewires your nervous system" },
      { imageUrl: U("1522202176988-66273c2fd55f"), text: "3. Journal for 10 minutes — get the chaos out of your head" },
      { imageUrl: U("1490730141103-6cac27aaab94"), text: "4. Cut out one toxic person this month" },
      { imageUrl: U("1552374196-c4e7ffc6e126"), text: "5. Move your body EVERY single day, no excuses" },
      { imageUrl: U("1486312338219-ce68d2c6f44d"), text: "6. Read 20 pages before bed instead of scrolling" },
      { imageUrl: U("1502823403499-6ccfcf4fb453"), text: "7. Speak your affirmations OUT LOUD" },
    ],
  },
  {
    id: 3,
    caption: "my lashes when I was 15 vs now... I will NEVER recommend lash serums again",
    subCaption: null,
    contentType: "slideshow",
    tags: ["B2C App", "Beauty"],
    num_likes: 4200,
    num_views: 271000,
    videoUrl: V(2),
    thumbnail: U("1534528741775-53994a69daeb"),
    slides: [
      { imageUrl: U("1524504388940-b1c1722653e1"), text: "My lashes at 15 — long, thick, natural" },
      { imageUrl: U("1488426862026-3ee34a7d66df"), text: "Started using lash serums at 19..." },
      { imageUrl: U("1531746020798-e6953c6e8e04"), text: "6 months later — they started FALLING OUT" },
      { imageUrl: U("1542206395-9feb3edaa68d"), text: "The damage was real. Had to stop everything." },
      { imageUrl: U("1499557354967-2b2d8910bcca"), text: "What actually helped: castor oil + biotin. That's IT." },
    ],
  },
  {
    id: 4,
    caption: "The AURA that everyone wants but nobody talks about",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Spirituality", "Self Improvement"],
    num_likes: 1100,
    num_views: 33100,
    videoUrl: V(3),
    thumbnail: U("1573496359142-b8d87734a5a2"),
    slides: [
      { imageUrl: U("1571019613454-1cb2f99b2d8b"), text: "The AURA everyone wants but nobody talks about" },
      { imageUrl: U("1486312338219-ce68d2c6f44d"), text: "It's not confidence. It's CALMNESS." },
      { imageUrl: U("1490730141103-6cac27aaab94"), text: "People with the best aura don't react — they respond." },
      { imageUrl: U("1522202176988-66273c2fd55f"), text: "They don't chase — they attract." },
    ],
  },
  {
    id: 5,
    caption: "5 things no one tells you about corporate",
    subCaption: null,
    contentType: "slideshow",
    tags: ["B2B App", "B2B SaaS/Platform"],
    num_likes: 1100,
    num_views: 33100,
    videoUrl: V(4),
    thumbnail: U("1553877522-43269d4ea984"),
    slides: [
      { imageUrl: U("1460925895917-afdab827c52f"), text: "1. Your manager's job is to manage UP, not help YOU" },
      { imageUrl: U("1551434678-e076c223a692"), text: "2. HR is there to protect the company, not you" },
      { imageUrl: U("1519389950473-47ba0277781c"), text: "3. The loudest person in meetings usually gets promoted first" },
      { imageUrl: U("1553877522-43269d4ea984"), text: "4. 'We're a family' = we expect you to work weekends" },
      { imageUrl: U("1556761175-5973dc0f32e7"), text: "5. Your side hustle should be ready before you quit" },
    ],
  },
  {
    id: 6,
    caption: "self improvement tips NOT worth your energy",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Self Improvement", "Productivity"],
    num_likes: 10800,
    num_views: 103500,
    videoUrl: V(5),
    thumbnail: U("1502823403499-6ccfcf4fb453"),
    slides: [
      { imageUrl: U("1493770348161-369560ae357d"), text: "Waking up at 4am just to say you did it" },
      { imageUrl: U("1571019613454-1cb2f99b2d8b"), text: "Cold plunges without understanding WHY" },
      { imageUrl: U("1522202176988-66273c2fd55f"), text: "Reading 50 books a year but retaining nothing" },
      { imageUrl: U("1490730141103-6cac27aaab94"), text: "Journaling if it feels like a chore" },
      { imageUrl: U("1486312338219-ce68d2c6f44d"), text: "Cutting off EVERYONE toxic without self-reflection" },
    ],
  },
  {
    id: 7,
    caption: "Weird habits I stole from attractive people",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Self Improvement", "Personal Brand"],
    num_likes: 135000,
    num_views: 1000000,
    videoUrl: V(6),
    thumbnail: U("1517841905240-472988babdf9"),
    slides: [
      { imageUrl: U("1484480974693-6ca0a78fb36b"), text: "They never explain themselves too much" },
      { imageUrl: U("1515378960530-7c0da6231ae1"), text: "They make eye contact 2 seconds longer than normal" },
      { imageUrl: U("1502823403499-6ccfcf4fb453"), text: "They ask YOUR name first and remember it" },
      { imageUrl: U("1522202176988-66273c2fd55f"), text: "They dress 10% better than the occasion requires" },
      { imageUrl: U("1486312338219-ce68d2c6f44d"), text: "They leave conversations BEFORE it gets boring" },
      { imageUrl: U("1493770348161-369560ae357d"), text: "They compliment specifics, never generics" },
    ],
  },
  {
    id: 8,
    caption: "Luxury Starter Pack for girls in their 30s | De-Influence",
    subCaption: null,
    contentType: "slideshow",
    tags: ["B2C App", "Beauty"],
    num_likes: 191000,
    num_views: 1500000,
    videoUrl: V(7),
    thumbnail: U("1438761681033-6461ffad8d80"),
    slides: [
      { imageUrl: U("1524504388940-b1c1722653e1"), text: "You do NOT need a $300 face cream" },
      { imageUrl: U("1488426862026-3ee34a7d66df"), text: "Invest in ONE good bag instead of 10 trendy ones" },
      { imageUrl: U("1531746020798-e6953c6e8e04"), text: "Real luxury? A full 8 hours of sleep." },
      { imageUrl: U("1499557354967-2b2d8910bcca"), text: "The most expensive thing you can wear is CONFIDENCE" },
    ],
  },
  {
    id: 9,
    caption: "exposing the self improvement tips that are NOT worth your time",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Self Improvement", "B2C App"],
    num_likes: 191000,
    num_views: 1500000,
    videoUrl: V(0),
    thumbnail: U("1542206395-9feb3edaa68d"),
    slides: [
      { imageUrl: U("1490730141103-6cac27aaab94"), text: "Dopamine detoxes — your brain doesn't work like that" },
      { imageUrl: U("1486312338219-ce68d2c6f44d"), text: "Monk mode for months — you'll just burn out" },
      { imageUrl: U("1493770348161-369560ae357d"), text: "Trying to be productive 24/7 — rest IS productive" },
      { imageUrl: U("1571019613454-1cb2f99b2d8b"), text: "Positive affirmations without action = delusion" },
      { imageUrl: U("1522202176988-66273c2fd55f"), text: "Comparison disguised as 'motivation'" },
    ],
  },
  {
    id: 10,
    caption: "The law of assumption explained like you're five years old",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Spirituality", "Course/Digital Product", "Personal Brand"],
    num_likes: 134800,
    num_views: 855000,
    videoUrl: V(1),
    thumbnail: U("1580489944761-15a19d654956"),
    slides: [
      { imageUrl: U("1484480974693-6ca0a78fb36b"), text: "Imagine you REALLY want a cookie..." },
      { imageUrl: U("1515378960530-7c0da6231ae1"), text: "Instead of wishing for it, you DECIDE: I'm getting that cookie." },
      { imageUrl: U("1502823403499-6ccfcf4fb453"), text: "You walk to the kitchen like it's ALREADY yours." },
      { imageUrl: U("1522202176988-66273c2fd55f"), text: "That's the law of assumption. You assume it's done." },
      { imageUrl: U("1486312338219-ce68d2c6f44d"), text: "Your brain literally cannot tell the difference between assumption and reality." },
    ],
  },
  {
    id: 11,
    caption: "networking hacks that taught me influence",
    subCaption: null,
    contentType: "slideshow",
    tags: ["B2B App", "Personal Brand"],
    num_likes: 16200,
    num_views: 144500,
    videoUrl: V(2),
    thumbnail: U("1522071820081-009f0129c71c"),
    slides: [
      { imageUrl: U("1519389950473-47ba0277781c"), text: "Never eat lunch alone. Every meal is a meeting." },
      { imageUrl: U("1460925895917-afdab827c52f"), text: "Follow up within 24 hours or you're forgotten" },
      { imageUrl: U("1551434678-e076c223a692"), text: "Give value FIRST. Ask for nothing." },
      { imageUrl: U("1553877522-43269d4ea984"), text: "Be the connector — introduce people to each other" },
      { imageUrl: U("1522071820081-009f0129c71c"), text: "Your network is your net worth. Protect it." },
    ],
  },
  {
    id: 12,
    caption: "If I was unemployed in 2026, this would be my 30-day plan to get hired",
    subCaption: null,
    contentType: "slideshow",
    tags: ["B2B App", "B2B SaaS/Platform"],
    num_likes: 48000,
    num_views: 480000,
    videoUrl: V(3),
    thumbnail: U("1500648767791-00dcc994a43e"),
    slides: [
      { imageUrl: U("1460925895917-afdab827c52f"), text: "Day 1-7: Rebuild your LinkedIn from scratch" },
      { imageUrl: U("1551434678-e076c223a692"), text: "Day 8-14: DM 50 people at companies you want to work at" },
      { imageUrl: U("1553877522-43269d4ea984"), text: "Day 15-21: Create 1 piece of content daily showing your skills" },
      { imageUrl: U("1522071820081-009f0129c71c"), text: "Day 22-28: Apply to 10 jobs/day with CUSTOM cover letters" },
      { imageUrl: U("1556761175-5973dc0f32e7"), text: "Day 29-30: Follow up on EVERYTHING. The fortune is in the follow-up." },
    ],
  },
  {
    id: 13,
    caption: "3 apps that replaced my entire morning routine",
    subCaption: null,
    contentType: "slideshow",
    tags: ["B2C App", "Productivity"],
    num_likes: 87000,
    num_views: 2100000,
    videoUrl: V(4),
    thumbnail: U("1502823403499-6ccfcf4fb453"),
    slides: [
      { imageUrl: U("1515378960530-7c0da6231ae1"), text: "App 1: Rise — AI alarm that wakes you during light sleep" },
      { imageUrl: U("1502823403499-6ccfcf4fb453"), text: "App 2: Notion Calendar — blocks my whole day automatically" },
      { imageUrl: U("1519389950473-47ba0277781c"), text: "App 3: Headspace — 5 min meditation changed everything" },
      { imageUrl: U("1484480974693-6ca0a78fb36b"), text: "Total time saved per day: 47 minutes" },
    ],
  },
  {
    id: 14,
    caption: "Things I stopped buying after turning 25",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Finance", "Self Improvement"],
    num_likes: 142000,
    num_views: 3400000,
    videoUrl: V(5),
    thumbnail: U("1499557354967-2b2d8910bcca"),
    slides: [
      { imageUrl: U("1484480974693-6ca0a78fb36b"), text: "Fast fashion — quality over quantity always wins" },
      { imageUrl: U("1515378960530-7c0da6231ae1"), text: "Alcohol every weekend — my skin and wallet thanked me" },
      { imageUrl: U("1502823403499-6ccfcf4fb453"), text: "New phone every year — last year's model works fine" },
      { imageUrl: U("1522202176988-66273c2fd55f"), text: "Subscriptions I never use — audit your bank statement monthly" },
      { imageUrl: U("1486312338219-ce68d2c6f44d"), text: "Expensive coffee daily — home brew saves $150/month" },
    ],
  },
  {
    id: 15,
    caption: "how to mass DM on Instagram without getting banned",
    subCaption: null,
    contentType: "slideshow",
    tags: ["B2B SaaS/Platform", "Personal Brand"],
    num_likes: 56000,
    num_views: 890000,
    videoUrl: V(6),
    thumbnail: U("1556761175-5973dc0f32e7"),
    slides: [
      { imageUrl: U("1460925895917-afdab827c52f"), text: "Step 1: Warm up your account for 2 weeks first" },
      { imageUrl: U("1556761175-5973dc0f32e7"), text: "Step 2: Max 20 DMs per hour, vary the message" },
      { imageUrl: U("1519389950473-47ba0277781c"), text: "Step 3: NEVER copy-paste the same message twice" },
      { imageUrl: U("1522071820081-009f0129c71c"), text: "Step 4: Use voice notes — 3x higher response rate" },
      { imageUrl: U("1551434678-e076c223a692"), text: "Step 5: Engage with their content BEFORE you DM" },
    ],
  },
  {
    id: 16,
    caption: "green flags in a man that women ignore",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Relationships", "Self Improvement"],
    num_likes: 210000,
    num_views: 5200000,
    videoUrl: V(7),
    thumbnail: U("1534528741775-53994a69daeb"),
    slides: [
      { imageUrl: U("1493770348161-369560ae357d"), text: "He remembers small details you mentioned once" },
      { imageUrl: U("1571019613454-1cb2f99b2d8b"), text: "He's kind to waitstaff and strangers" },
      { imageUrl: U("1522202176988-66273c2fd55f"), text: "He doesn't need to be the center of attention" },
      { imageUrl: U("1490730141103-6cac27aaab94"), text: "He apologizes without making excuses" },
      { imageUrl: U("1486312338219-ce68d2c6f44d"), text: "He's genuinely happy when you succeed" },
    ],
  },
  {
    id: 17,
    caption: "SaaS tools I use to run my $10k/mo business solo",
    subCaption: null,
    contentType: "slideshow",
    tags: ["B2B SaaS/Platform", "Productivity"],
    num_likes: 78000,
    num_views: 1600000,
    videoUrl: V(0),
    thumbnail: U("1519389950473-47ba0277781c"),
    slides: [
      { imageUrl: U("1460925895917-afdab827c52f"), text: "Stripe for payments — $0 setup, instant payouts" },
      { imageUrl: U("1551434678-e076c223a692"), text: "Notion for everything — CRM, docs, wiki, project mgmt" },
      { imageUrl: U("1553877522-43269d4ea984"), text: "Vercel for hosting — push to deploy in seconds" },
      { imageUrl: U("1556761175-5973dc0f32e7"), text: "Resend for emails — beautiful transactional emails" },
      { imageUrl: U("1519389950473-47ba0277781c"), text: "Total cost: $67/month. Revenue: $10,400/month." },
    ],
  },
  {
    id: 18,
    caption: "foods that are secretly destroying your gut",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Health", "B2C App"],
    num_likes: 165000,
    num_views: 4100000,
    videoUrl: V(1),
    thumbnail: U("1504674900247-0877df9cc836"),
    slides: [
      { imageUrl: U("1504674900247-0877df9cc836"), text: "Seed oils — in literally EVERYTHING at restaurants" },
      { imageUrl: U("1546069901-ba9599a7e63c"), text: "Diet sodas — artificial sweeteners destroy gut bacteria" },
      { imageUrl: U("1498837167922-ddd27525d352"), text: "Protein bars — most are just candy bars with marketing" },
      { imageUrl: U("1544027993-215b52be37e5"), text: "Store-bought bread — check for high fructose corn syrup" },
      { imageUrl: U("1504674900247-0877df9cc836"), text: "Your gut heals in 3-4 weeks once you cut these out" },
    ],
  },
  {
    id: 19,
    caption: "the dark side of manifestation no one talks about",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Spirituality", "Self Improvement"],
    num_likes: 94000,
    num_views: 2300000,
    videoUrl: V(2),
    thumbnail: U("1571019613454-1cb2f99b2d8b"),
    slides: [
      { imageUrl: U("1571019613454-1cb2f99b2d8b"), text: "Manifestation without action is just daydreaming" },
      { imageUrl: U("1522202176988-66273c2fd55f"), text: "It can make you blame yourself for things outside your control" },
      { imageUrl: U("1486312338219-ce68d2c6f44d"), text: "Some people use it to avoid therapy" },
      { imageUrl: U("1490730141103-6cac27aaab94"), text: "The universe doesn't owe you anything. You owe yourself action." },
    ],
  },
  {
    id: 20,
    caption: "workout split that changed my physique in 90 days",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Fitness", "B2C App"],
    num_likes: 118000,
    num_views: 2800000,
    videoUrl: V(3),
    thumbnail: U("1552374196-c4e7ffc6e126"),
    slides: [
      { imageUrl: U("1571019614242-c5c5dee9f50b"), text: "Monday: Push (chest, shoulders, triceps)" },
      { imageUrl: U("1548690312-e3b507d8c110"), text: "Tuesday: Pull (back, biceps, rear delts)" },
      { imageUrl: U("1552374196-c4e7ffc6e126"), text: "Wednesday: Legs (quads, hamstrings, calves)" },
      { imageUrl: U("1490730141103-6cac27aaab94"), text: "Thursday: Rest + 30 min walk" },
      { imageUrl: U("1571019614242-c5c5dee9f50b"), text: "Friday: Upper body (compounds only)" },
      { imageUrl: U("1548690312-e3b507d8c110"), text: "Saturday: Lower body + core" },
    ],
  },
  {
    id: 21,
    caption: "AI tools that will replace your marketing team",
    subCaption: null,
    contentType: "slideshow",
    tags: ["B2B SaaS/Platform", "Productivity"],
    num_likes: 203000,
    num_views: 4800000,
    videoUrl: V(4),
    thumbnail: U("1553877522-43269d4ea984"),
    slides: [
      { imageUrl: U("1460925895917-afdab827c52f"), text: "Jasper AI — writes better copy than most junior marketers" },
      { imageUrl: U("1551434678-e076c223a692"), text: "Midjourney — unlimited creative assets for $10/mo" },
      { imageUrl: U("1553877522-43269d4ea984"), text: "Opus Clip — turns 1 long video into 10 viral shorts" },
      { imageUrl: U("1556761175-5973dc0f32e7"), text: "Instantly.ai — cold email at scale without getting flagged" },
      { imageUrl: U("1519389950473-47ba0277781c"), text: "Total savings: ~$8k/month in salaries" },
    ],
  },
  {
    id: 22,
    caption: "money habits keeping you broke in your 20s",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Finance", "Self Improvement"],
    num_likes: 176000,
    num_views: 3900000,
    videoUrl: V(5),
    thumbnail: U("1484480974693-6ca0a78fb36b"),
    slides: [
      { imageUrl: U("1484480974693-6ca0a78fb36b"), text: "Lifestyle inflation — earning more but saving less" },
      { imageUrl: U("1515378960530-7c0da6231ae1"), text: "No emergency fund — one car repair away from debt" },
      { imageUrl: U("1502823403499-6ccfcf4fb453"), text: "Only saving, never investing — inflation eats your savings" },
      { imageUrl: U("1522202176988-66273c2fd55f"), text: "Ignoring your credit score — it affects EVERYTHING" },
      { imageUrl: U("1486312338219-ce68d2c6f44d"), text: "Paying minimums on credit cards — the interest is INSANE" },
    ],
  },
  {
    id: 23,
    caption: "How to romanticize discipline without burning out",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Self Improvement", "Productivity"],
    num_likes: 97000,
    num_views: 2400000,
    videoUrl: V(6),
    thumbnail: U("1493770348161-369560ae357d"),
    slides: [
      { imageUrl: U("1493770348161-369560ae357d"), text: "Stop treating discipline like punishment" },
      { imageUrl: U("1486312338219-ce68d2c6f44d"), text: "Make your morning routine something you LOOK FORWARD to" },
      { imageUrl: U("1502823403499-6ccfcf4fb453"), text: "Discipline ≠ suffering. It's choosing your hard." },
      { imageUrl: U("1522202176988-66273c2fd55f"), text: "Romanticize the mundane — the commute, the prep, the grind" },
      { imageUrl: U("1515378960530-7c0da6231ae1"), text: "Rest is part of discipline. Recovery is not laziness." },
    ],
  },
  {
    id: 24,
    caption: "skincare routine that cleared my hormonal acne in 8 weeks",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Beauty", "B2C App", "Health"],
    num_likes: 228000,
    num_views: 5100000,
    videoUrl: V(7),
    thumbnail: U("1531746020798-e6953c6e8e04"),
    slides: [
      { imageUrl: U("1524504388940-b1c1722653e1"), text: "Step 1: Gentle cleanser — stop stripping your skin barrier" },
      { imageUrl: U("1488426862026-3ee34a7d66df"), text: "Step 2: Niacinamide serum — 10% concentration max" },
      { imageUrl: U("1534528741775-53994a69daeb"), text: "Step 3: Azelaic acid 15% — the REAL acne killer" },
      { imageUrl: U("1542206395-9feb3edaa68d"), text: "Step 4: Moisturize even if you're oily — dehydrated skin overproduces oil" },
      { imageUrl: U("1499557354967-2b2d8910bcca"), text: "Step 5: SPF 50 EVERY DAY — non-negotiable" },
      { imageUrl: U("1531746020798-e6953c6e8e04"), text: "Bonus: Cut dairy and sugar for 30 days. My skin literally GLOWED." },
    ],
  },
  {
    id: 25,
    caption: "how I built a $5k/mo side hustle in 90 days with zero audience",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Course/Digital Product", "Personal Brand", "Finance"],
    num_likes: 153000,
    num_views: 3600000,
    videoUrl: V(0),
    thumbnail: U("1460925895917-afdab827c52f"),
    slides: [
      { imageUrl: U("1460925895917-afdab827c52f"), text: "Week 1-2: Picked ONE skill I was already good at" },
      { imageUrl: U("1551434678-e076c223a692"), text: "Week 3-4: Built a simple Notion template and priced it at $27" },
      { imageUrl: U("1519389950473-47ba0277781c"), text: "Week 5-8: Posted 2 TikToks/day showing the results of using it" },
      { imageUrl: U("1553877522-43269d4ea984"), text: "Week 9-10: One video hit 800K views — 340 sales in 48 hours" },
      { imageUrl: U("1522071820081-009f0129c71c"), text: "Week 11-12: Created a $97 bundle. Revenue: $5,200/month" },
      { imageUrl: U("1556761175-5973dc0f32e7"), text: "The secret: solve ONE problem. Package it beautifully. Distribute relentlessly." },
    ],
  },
  {
    id: 26,
    caption: "supplements I take daily as a woman in her 20s",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Supplement", "Health", "Beauty"],
    num_likes: 189000,
    num_views: 4500000,
    videoUrl: V(1),
    thumbnail: U("1438761681033-6461ffad8d80"),
    slides: [
      { imageUrl: U("1544027993-215b52be37e5"), text: "Magnesium glycinate — sleep, mood, cramps. A game-changer." },
      { imageUrl: U("1504674900247-0877df9cc836"), text: "Iron + Vitamin C — most women are low and don't know it" },
      { imageUrl: U("1546069901-ba9599a7e63c"), text: "Omega-3 fish oil — skin glow + brain fog gone" },
      { imageUrl: U("1498837167922-ddd27525d352"), text: "Vitamin D3 + K2 — especially if you're indoors a lot" },
      { imageUrl: U("1544027993-215b52be37e5"), text: "Probiotics — gut health = skin health = mental health" },
    ],
  },
  {
    id: 27,
    caption: "things I wish I knew before starting my e-commerce brand",
    subCaption: null,
    contentType: "slideshow",
    tags: ["E-Commerce", "B2B SaaS/Platform"],
    num_likes: 67000,
    num_views: 1800000,
    videoUrl: V(2),
    thumbnail: U("1551434678-e076c223a692"),
    slides: [
      { imageUrl: U("1460925895917-afdab827c52f"), text: "Your product photos matter more than your product (at first)" },
      { imageUrl: U("1553877522-43269d4ea984"), text: "UGC ads outperform studio ads 9 times out of 10" },
      { imageUrl: U("1556761175-5973dc0f32e7"), text: "Email marketing makes more money than social media. Period." },
      { imageUrl: U("1519389950473-47ba0277781c"), text: "Don't launch with 50 SKUs. Launch with 3 and nail them." },
      { imageUrl: U("1551434678-e076c223a692"), text: "Your first 100 customers should feel like VIPs, not transactions." },
    ],
  },
  {
    id: 28,
    caption: "5 things I do every Sunday to have a productive week",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Productivity", "Self Improvement"],
    num_likes: 114000,
    num_views: 2700000,
    videoUrl: V(3),
    thumbnail: U("1522202176988-66273c2fd55f"),
    slides: [
      { imageUrl: U("1522202176988-66273c2fd55f"), text: "1. Brain dump — write down EVERYTHING in my head" },
      { imageUrl: U("1502823403499-6ccfcf4fb453"), text: "2. Plan 3 non-negotiable tasks for each day" },
      { imageUrl: U("1515378960530-7c0da6231ae1"), text: "3. Meal prep — decision fatigue is real" },
      { imageUrl: U("1493770348161-369560ae357d"), text: "4. Review last week — what worked? what didn't?" },
      { imageUrl: U("1486312338219-ce68d2c6f44d"), text: "5. Clean my workspace — cluttered desk = cluttered mind" },
    ],
  },
  {
    id: 29,
    caption: "the psychology behind why you can't stop scrolling",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Course/Digital Product", "Health"],
    num_likes: 245000,
    num_views: 5800000,
    videoUrl: V(4),
    thumbnail: U("1574279606264-2f5d3fb6a4b5"),
    slides: [
      { imageUrl: U("1574279606264-2f5d3fb6a4b5"), text: "Variable reward schedules — same mechanism as slot machines" },
      { imageUrl: U("1502823403499-6ccfcf4fb453"), text: "Infinite scroll removes natural stopping cues" },
      { imageUrl: U("1515378960530-7c0da6231ae1"), text: "Social validation = dopamine. Every like hits your reward center." },
      { imageUrl: U("1484480974693-6ca0a78fb36b"), text: "FOMO is manufactured — notifications are designed to pull you back" },
      { imageUrl: U("1486312338219-ce68d2c6f44d"), text: "The cure: time limits, grayscale mode, and being honest with yourself" },
    ],
  },
  {
    id: 30,
    caption: "how to talk to anyone (from an extreme introvert)",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Personal Brand", "Self Improvement"],
    num_likes: 320000,
    num_views: 5500000,
    videoUrl: V(5),
    thumbnail: U("1560250097-0b93528c311a"),
    slides: [
      { imageUrl: U("1507003211169-0a1dd7228f2d"), text: "Ask about THEM first. People love talking about themselves." },
      { imageUrl: U("1506794778202-cad84cf45f1d"), text: "Mirror their energy — don't be louder or quieter than them" },
      { imageUrl: U("1500648767791-00dcc994a43e"), text: "Use their name. It's the sweetest sound to anyone." },
      { imageUrl: U("1560250097-0b93528c311a"), text: "Give genuine compliments on things they CHOSE (outfit, ideas), not genetics" },
      { imageUrl: U("1548690312-e3b507d8c110"), text: "Leave while the conversation is still good. Always leave them wanting more." },
    ],
  },
  {
    id: 31,
    caption: "my protein-packed meals that actually taste insane",
    subCaption: null,
    contentType: "slideshow",
    tags: ["Fitness", "Health", "Supplement"],
    num_likes: 167000,
    num_views: 3200000,
    videoUrl: V(6),
    thumbnail: U("1544027993-215b52be37e5"),
    slides: [
      { imageUrl: U("1504674900247-0877df9cc836"), text: "Meal 1: Greek yogurt + protein powder + frozen berries (42g protein)" },
      { imageUrl: U("1546069901-ba9599a7e63c"), text: "Meal 2: Ground turkey stir-fry with rice and veggies (55g protein)" },
      { imageUrl: U("1498837167922-ddd27525d352"), text: "Meal 3: Salmon bowl with sweet potato and avocado (48g protein)" },
      { imageUrl: U("1544027993-215b52be37e5"), text: "Meal 4: Cottage cheese with honey and almonds before bed (30g protein)" },
      { imageUrl: U("1504674900247-0877df9cc836"), text: "Total: 175g protein. Tastes AMAZING. No chicken breast in sight." },
    ],
  },
  {
    id: 32,
    caption: "red flags in a job interview they hope you don't notice",
    subCaption: null,
    contentType: "slideshow",
    tags: ["B2B App", "B2B SaaS/Platform", "Productivity"],
    num_likes: 289000,
    num_views: 5900000,
    videoUrl: V(7),
    thumbnail: U("1508341591423-4347099e1f19"),
    slides: [
      { imageUrl: U("1556761175-5973dc0f32e7"), text: "'We work hard and play hard' = no work-life balance" },
      { imageUrl: U("1553877522-43269d4ea984"), text: "'We're like a family here' = guilt trips when you set boundaries" },
      { imageUrl: U("1522071820081-009f0129c71c"), text: "Interviewer can't clearly explain the role = they don't know what they need" },
      { imageUrl: U("1508341591423-4347099e1f19"), text: "Glassdoor reviews all say the same negative thing = it's true" },
      { imageUrl: U("1460925895917-afdab827c52f"), text: "They rush the salary conversation = the offer will be low" },
      { imageUrl: U("1551434678-e076c223a692"), text: "High turnover rate = something is deeply wrong with management" },
    ],
  },

  // ====================  WALL OF TEXT (33–58)  ====================
  {
    id: 33,
    caption: "what I wish I knew when I was unemployed for 6 MONTHS",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["B2B App", "B2C App"],
    num_likes: 18300,
    num_views: 428000,
    videoUrl: V(4),
    thumbnail: U("1507003211169-0a1dd7228f2d"),
    textOverlay: "I was unemployed for 6 months in 2024 and nobody prepared me for how lonely it would be. You wake up and everyone you know is at work. Your routine disappears. You start doubting everything about yourself.\n\nHere's what I wish someone told me: the job market is NOT a reflection of your worth. I applied to 400+ jobs. Got 12 interviews. 2 offers. That's a 0.5% conversion rate. It's a numbers game, not a you game.\n\nThe thing that actually got me hired? I stopped applying online and started DMing founders directly on LinkedIn. Within 2 weeks of switching strategies, I had 5 interviews lined up. The job I got? It wasn't even posted anywhere.\n\nStop playing the application game. Start playing the relationship game.",
  },
  {
    id: 34,
    caption: "what my husband told me to do... until I started mothering him.",
    subCaption: "If you're tired of feeling like a mom instead of his wife, listen up.",
    contentType: "wall-of-text",
    tags: ["Relationships", "Self Improvement"],
    num_likes: 24600,
    num_views: 682000,
    videoUrl: V(5),
    thumbnail: U("1494790108377-be9c29b29330"),
    textOverlay: "My husband used to leave his clothes on the floor, forget to take out the trash, and I'd remind him 47 times like I was his mother. I was exhausted. Resentful. And honestly? Starting to lose attraction.\n\nThen I read something that changed everything: 'You cannot mother a man and be attracted to him at the same time.' That hit different.\n\nSo I stopped. I stopped reminding. I stopped picking up after him. Was it messy for a few weeks? YES. Did he notice? Eventually.\n\nBut here's the magic: when I stopped mothering him, he started SHOWING UP. Not because I nagged, but because I created space for him to step up. Men rise to the occasion when you stop lowering the bar.\n\nYour marriage is not your management project. Let him be a grown man.",
  },
  {
    id: 35,
    caption: "career tips I wish someone told me at 20",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["B2C App", "Self Improvement", "Productivity"],
    num_likes: 34000,
    num_views: 1100000,
    videoUrl: V(6),
    thumbnail: U("1506794778202-cad84cf45f1d"),
    textOverlay: "I'm 32 now and if I could go back to 20, here's what I'd tell myself:\n\nYour first job doesn't define your career. I spent 3 years at a company I hated because I thought leaving would look bad on my resume. Nobody cares. Move faster.\n\nLearn to write well. I don't care what field you're in. The person who can write a clear email, a persuasive proposal, or a compelling LinkedIn post will ALWAYS have opportunities.\n\nYour network matters more than your GPA. I got my best job through someone I met at a random coffee shop. Start talking to people.\n\nSave 6 months of expenses before you ever think about entrepreneurship. I learned this the hard way.\n\nAnd the biggest one: bet on yourself earlier. Every year you wait is a year of compound growth you'll never get back.",
  },
  {
    id: 36,
    caption: "how I changed my marriage in 6 months",
    subCaption: "And many others are doing the same",
    contentType: "wall-of-text",
    tags: ["Relationships", "Self Improvement"],
    num_likes: 25500,
    num_views: 191000,
    videoUrl: V(7),
    thumbnail: U("1517841905240-472988babdf9"),
    textOverlay: "3 years ago my marriage was on the edge. We were roommates who slept in the same bed. No intimacy, no connection, just logistics about the kids and the house.\n\nI tried everything — date nights, couples therapy, love languages quiz. Nothing stuck. Then I realized the problem wasn't us. It was ME.\n\nI had stopped being the person my partner fell in love with. I stopped working on myself. I stopped having my own goals, my own excitement.\n\nSo I started investing in myself again. Gym 4x a week. Reading. Starting a side project. Getting therapy on my own.\n\nAnd slowly, my partner started noticing. Not because I was doing it for them — but because I was becoming magnetic again. You can't pour from an empty cup, and you can't attract someone when you've stopped being attractive to yourself.",
  },
  {
    id: 37,
    caption: "things I started doing outside the gym that 10x'd my results",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["Fitness", "Health"],
    num_likes: 64200,
    num_views: 221200,
    videoUrl: V(0),
    thumbnail: U("1548690312-e3b507d8c110"),
    textOverlay: "I trained for 3 years and looked basically the same. Frustrated doesn't even cover it. Then I realized the gym was only 20% of the equation.\n\nHere's what actually moved the needle:\n\nSleep: I went from 6 hours to 7.5 hours. That alone changed my recovery more than any supplement ever did. Your muscles grow when you SLEEP, not when you lift.\n\nProtein: I was eating 80g a day thinking it was enough. Bumped it to 160g and within 6 weeks people were asking if I was on something.\n\nSteps: 10,000 steps a day. Not for cardio. For NEAT (non-exercise activity thermogenesis). This is the #1 fat loss hack nobody talks about.\n\nStress: Cortisol literally eats muscle. I started meditating 10 min/day and my waistline shrank without changing my diet.\n\nThe gym is the stimulus. Everything outside the gym is the response. Fix the response.",
  },
  {
    id: 38,
    caption: "manager hacks that keep me from drowning in tasks",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["B2B App", "Productivity"],
    num_likes: 16800,
    num_views: 144500,
    videoUrl: V(1),
    thumbnail: U("1500648767791-00dcc994a43e"),
    textOverlay: "I manage a team of 12 and used to work 60+ hours a week. Now I work 38 and my team performs better than ever. Here's exactly what changed:\n\nI stopped being in every meeting. If I don't NEED to be there, I don't go. I read the notes in 2 minutes instead of sitting through a 45-minute call.\n\nI batch my 1:1s on Tuesdays. Every single one, back to back. Yes it's intense for 3 hours but then I have the rest of the week to actually DO work.\n\nI created a 'decision tree' doc. 90% of questions my team asks me have predictable answers. Now they check the doc first. My Slack messages dropped by 60%.\n\nManagement isn't about doing more. It's about designing systems so you can do less.",
  },
  {
    id: 39,
    caption: "baddie to baddie, what's something that's made your mental health go from 'I hate my life' to 'I can't wait for tomorrow'??",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["B2C App", "Self Improvement"],
    num_likes: 42100,
    num_views: 1200000,
    videoUrl: V(2),
    thumbnail: U("1580489944761-15a19d654956"),
    textOverlay: "I'll go first. Two years ago I was crying in my car every day after work. I dreaded mornings. I had no energy, no motivation, and honestly no hope.\n\nHere's what changed:\n\n1. I got on the right medication. No shame. My brain chemistry was off and no amount of journaling was going to fix a serotonin deficiency.\n\n2. I cut out 3 people who were draining me. Sounds harsh but boundaries literally saved my life.\n\n3. I found ONE thing to look forward to each day. Even if it was just my favorite coffee.\n\n4. I stopped comparing my chapter 1 to someone else's chapter 20.\n\n5. I started moving my body. Not to lose weight. Just to FEEL something other than numb. A 20-minute walk changed more than 2 years of overthinking.\n\nYou're not broken. You're just in a season. And seasons change.",
  },
  {
    id: 40,
    caption: "unpopular opinion: cold showers are overhyped and here's why",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["Health", "Self Improvement"],
    num_likes: 52000,
    num_views: 1200000,
    videoUrl: V(3),
    thumbnail: U("1506794778202-cad84cf45f1d"),
    textOverlay: "Before you come at me in the comments, hear me out.\n\nCold showers have real benefits — reduced inflammation, improved circulation, mental resilience. I'm not denying the science.\n\nBut here's what the 'cold shower bro' community won't tell you: if you're already stressed, under-slept, and running on cortisol, adding ANOTHER stressor to your morning is not the flex you think it is.\n\nYour body doesn't know the difference between 'good stress' and 'bad stress.' It just knows STRESS. And stacking stress leads to burnout, not breakthroughs.\n\nWhat actually works? Fix your sleep first. Get your nutrition right. Manage your mental health. THEN add cold exposure as a cherry on top.\n\nDoing cold showers while eating garbage and sleeping 5 hours is like putting premium gas in a car with flat tires.",
  },
  {
    id: 41,
    caption: "I quit my 6-figure job to build an app. Here's month 3.",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["B2B App", "Personal Brand"],
    num_likes: 89000,
    num_views: 2100000,
    videoUrl: V(4),
    thumbnail: U("1560250097-0b93528c311a"),
    textOverlay: "Month 1: Pure adrenaline. Woke up excited every day. Built the MVP in 3 weeks. Felt like a genius.\n\nMonth 2: Reality check. Launched to crickets. 14 signups, 2 paying users. Started doubting everything. My savings were burning faster than expected.\n\nMonth 3 (now): Something shifted. I stopped building features nobody asked for and started talking to users. Like actually calling them on the phone.\n\nTurns out the feature I thought was genius? Nobody cared. The one I almost deleted? That's what they actually wanted. I pivoted in 4 days. Revenue went from $40/month to $380/month.\n\nStill not enough to replace my salary. But the trajectory changed. The curve is pointing up.\n\nBiggest lesson: your customers will tell you exactly what to build. You just have to shut up and listen.",
  },
  {
    id: 42,
    caption: "the real reason your content isn't going viral",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["Personal Brand", "Course/Digital Product"],
    num_likes: 67000,
    num_views: 1500000,
    videoUrl: V(5),
    thumbnail: U("1573496359142-b8d87734a5a2"),
    textOverlay: "It's not the algorithm. It's not the timing. It's not that you need better lighting.\n\nYour content isn't going viral because you're making content for YOU, not for your AUDIENCE.\n\nEvery piece of content should answer ONE question: 'Why should someone who doesn't know me care about this?'\n\nIf your answer is 'because it's important to me' — that's a journal entry, not content.\n\nThe creators who blow up study what their audience is ALREADY searching for, ALREADY complaining about, ALREADY curious about. Then they package the answer in an entertaining way.\n\nStop trying to be original. Start being USEFUL. Originality comes from your unique perspective on common problems. Not from inventing problems nobody has.",
  },
  {
    id: 43,
    caption: "dating advice from someone who's been married 15 years",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["Relationships", "Self Improvement"],
    num_likes: 234000,
    num_views: 5600000,
    videoUrl: V(6),
    thumbnail: U("1507003211169-0a1dd7228f2d"),
    textOverlay: "Been with my wife for 15 years. Married for 12. Here's what I know for sure:\n\nThe butterflies go away. That's normal. What replaces them is better — it's a deep, quiet knowing that someone has your back. Don't chase the butterflies. Chase the peace.\n\nFight about the issue, not the person. 'You left the dishes out' is different from 'You're so lazy.' One is fixable. The other is an attack.\n\nHave your own thing. My wife has her book club. I have my basketball league. We don't share everything and that's HEALTHY.\n\nSay 'thank you' more than 'I love you.' Gratitude is the most underrated relationship tool.\n\nAnd the biggest one: choose them every day. Love isn't a feeling. It's a decision you make over and over, especially on the days you don't feel like it.",
  },
  {
    id: 44,
    caption: "supplements that actually work vs pure marketing",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["Health", "Supplement"],
    num_likes: 145000,
    num_views: 3200000,
    videoUrl: V(7),
    thumbnail: U("1552374196-c4e7ffc6e126"),
    textOverlay: "I spent $300/month on supplements for 2 years. Here's what actually works and what's a scam:\n\nACTUALLY WORKS:\n- Creatine monohydrate (5g/day). The most researched supplement in history.\n- Vitamin D3 (if you're deficient). Most people are. Get bloodwork first.\n- Magnesium glycinate (before bed). Better sleep, less anxiety.\n- Fish oil (high quality only). Reduces inflammation.\n\nPURE MARKETING:\n- BCAAs: If you eat enough protein, these are useless. Flavored water.\n- Fat burners: Just caffeine pills with a 10x markup.\n- Testosterone boosters: None of them work.\n- Greens powders: Just eat actual vegetables.\n\nTotal monthly cost of what actually works: about $35. Not $300.",
  },
  {
    id: 45,
    caption: "how I went from 0 to 100k followers in 6 months",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["Personal Brand", "Course/Digital Product"],
    num_likes: 198000,
    num_views: 4400000,
    videoUrl: V(0),
    thumbnail: U("1524504388940-b1c1722653e1"),
    textOverlay: "6 months ago I had 340 followers. Today I'm at 112k. No paid ads. No shoutouts. No buying followers. Here's exactly what I did:\n\nMonth 1-2: I posted every single day. 90% of it flopped. But I was learning what worked.\n\nMonth 3: One post hit 2M views. I studied it obsessively and made 15 variations of that same concept.\n\nMonth 4: I started engaging with EVERY comment in the first 60 minutes. The algorithm rewards conversations.\n\nMonth 5: I niched down HARD. Stopped trying to be everything to everyone.\n\nMonth 6: I launched a free resource that drove email signups. Now I own my audience, not the algorithm.\n\nGrowing fast isn't about going viral once. It's about being consistent enough that the algorithm TRUSTS you.",
  },
  {
    id: 46,
    caption: "toxic productivity habits disguised as hustle culture",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["Productivity", "Self Improvement"],
    num_likes: 112000,
    num_views: 2600000,
    videoUrl: V(1),
    thumbnail: U("1488426862026-3ee34a7d66df"),
    textOverlay: "Hustle culture almost destroyed me. Here are the 'productivity tips' that were actually toxic:\n\n'Sleep when you're dead.' I slept 4-5 hours for 2 years. My memory got worse, I got sick constantly, and my creativity tanked. Sleep is the #1 performance enhancer and it's FREE.\n\n'Always be grinding.' I worked 7 days a week and burned out so hard I couldn't work for 3 months. Rest is not laziness. It's maintenance.\n\n'Say yes to everything.' I said yes until my calendar was a war zone. Learning to say no was the most productive thing I ever did.\n\n'Wake up at 4am.' I'm not a morning person. Forcing it just meant I was tired AND unproductive by 2pm.\n\nReal productivity isn't about doing more. It's about doing less, better.",
  },
  {
    id: 47,
    caption: "things I learned losing $50k on my first startup",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["B2B App", "B2B SaaS/Platform"],
    num_likes: 76000,
    num_views: 1800000,
    videoUrl: V(2),
    thumbnail: U("1506794778202-cad84cf45f1d"),
    textOverlay: "In 2022 I quit my job, emptied my savings, and spent $50k building an app nobody wanted. Here are the expensive lessons:\n\nLesson 1: I built for 8 months before talking to a single customer. When I finally launched, I discovered the problem I was solving... wasn't actually a problem.\n\nLesson 2: I hired a fancy dev agency instead of learning to build myself. If I had spent 3 months learning to code, I could have built the MVP for $0.\n\nLesson 3: I told everyone about my idea and mistook their politeness for validation. The only validation that matters is someone pulling out their credit card.\n\nLesson 4: I didn't set a 'kill switch' — a date where I'd walk away. So I kept pouring money into a sinking ship.\n\nLesson 5: Failure isn't the opposite of success. It's the tuition. My second startup hit $10k MRR in 4 months because I made none of the same mistakes.",
  },
  {
    id: 48,
    caption: "I tracked every dollar for 365 days. here's what I found.",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["Finance", "Self Improvement"],
    num_likes: 134000,
    num_views: 3100000,
    videoUrl: V(3),
    thumbnail: U("1500648767791-00dcc994a43e"),
    textOverlay: "On January 1st last year I started logging every single purchase. Coffee, subscriptions, groceries, everything. Here's what 365 days taught me:\n\nI was spending $287/month on food delivery apps. TWO HUNDRED AND EIGHTY SEVEN. I could have bought a plane ticket every month for that.\n\nSubscriptions I forgot about were costing me $94/month. Gym I didn't go to, apps I didn't open, streaming services I didn't watch.\n\nMy 'I deserve this' purchases added up to $3,400 for the year. Every latte, every impulse Amazon buy, every 'treat yourself' moment.\n\nTotal wasted spending: $7,700/year. That's a vacation. That's an emergency fund. That's 6 months of investing.\n\nI'm not saying don't enjoy life. I'm saying KNOW where your money goes. Awareness alone cut my spending by 31%.",
  },
  {
    id: 49,
    caption: "the truth about working remotely that nobody posts about",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["B2B App", "Productivity"],
    num_likes: 93000,
    num_views: 2200000,
    videoUrl: V(4),
    thumbnail: U("1551434678-e076c223a692"),
    textOverlay: "Remote work is amazing. It's also incredibly lonely and nobody talks about it.\n\nYou save 2 hours on commuting. Great. You spend those 2 hours staring at the same walls. Your social skills start degrading. You forget how to make small talk.\n\nYour bedroom becomes your office becomes your gym becomes your everything. The boundaries between work and life don't blur — they dissolve.\n\nHere's what actually helps: Get dressed every morning like you're going somewhere. Work from a coffee shop at least twice a week. Schedule a non-work video call with a friend during lunch. Take a walk at 3pm when your brain turns to mush.\n\nAnd the biggest one: set a hard stop time. Close the laptop. Walk away. Your employer is renting your time, not buying your soul.\n\nRemote work is a privilege. But it requires more discipline than any office job ever did.",
  },
  {
    id: 50,
    caption: "as a therapist, here are things I wish all my clients knew",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["Health", "Self Improvement"],
    num_likes: 267000,
    num_views: 5800000,
    videoUrl: V(5),
    thumbnail: U("1573496359142-b8d87734a5a2"),
    textOverlay: "I've been a therapist for 11 years. Here's what I wish every client knew before their first session:\n\nTherapy is not advice-giving. I'm not going to tell you what to do. I'm going to help you figure out why you do what you do.\n\nIt gets worse before it gets better. Unpacking trauma is like cleaning a messy closet — you have to take everything out before you can organize it.\n\nYour therapist is not your friend. That's by design. The distance is what makes it safe.\n\nNot every therapist is the right fit. If after 3 sessions you don't feel comfortable, switch. It's not personal.\n\nAnd the biggest one: YOU do the work. I guide. You walk. The breakthroughs happen between sessions, not during them.\n\nMental health isn't a destination. It's maintenance. Like brushing your teeth but for your brain.",
  },
  {
    id: 51,
    caption: "I sell digital products and made $47k last month. here's my entire strategy.",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["Course/Digital Product", "Personal Brand", "E-Commerce"],
    num_likes: 178000,
    num_views: 4100000,
    videoUrl: V(6),
    thumbnail: U("1438761681033-6461ffad8d80"),
    textOverlay: "I sell Notion templates, Canva presets, and a $297 course. Last month: $47,200. Here's the strategy nobody wants to give away for free:\n\n1. I create one piece of free content every day that SOLVES a real problem. Not motivational fluff. Actual tutorials, frameworks, templates.\n\n2. Every free post has a soft CTA: 'I made a complete system for this — link in bio.' No hard selling. No countdown timers.\n\n3. My $9 product is the gateway drug. Once someone buys the $9 template and gets results, they trust me enough to buy the $297 course.\n\n4. Email list > everything. I send 3 emails a week. 2 value, 1 pitch. My email list converts at 4.2% — social media converts at 0.3%.\n\n5. I reinvest 20% of revenue into UGC ads from real customers showing their results.\n\nThe hardest part? The first $1,000. After that, it compounds.",
  },
  {
    id: 52,
    caption: "what nobody tells you about getting lean as a woman",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["Fitness", "Health"],
    num_likes: 203000,
    num_views: 4800000,
    videoUrl: V(7),
    thumbnail: U("1571019614242-c5c5dee9f50b"),
    textOverlay: "I spent 4 years trying to get lean and failing because I was following advice designed for MEN. Here's what actually works for women:\n\nYour cycle matters. During your luteal phase (week 3-4), your body burns more calories but also craves more carbs. Work WITH this, not against it.\n\nYou don't need a 500-calorie deficit. A 200-300 deficit is enough. Aggressive cuts crash your hormones, stall your metabolism, and make you lose muscle.\n\nCardio is overrated for fat loss. Strength training 4x/week changed my body more than 6 months of running ever did.\n\nStop weighing yourself daily. Your weight fluctuates 2-5 lbs based on water, hormones, and sleep. Take progress photos instead.\n\nAnd please eat more protein. Most women I coach eat 40-60g. You need at LEAST 100g. Your body can't build muscle without it.\n\nGetting lean as a woman isn't harder. It just requires different strategies.",
  },
  {
    id: 53,
    caption: "the moment I knew my 9-5 was actually killing me",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["B2C App", "Self Improvement", "Personal Brand"],
    num_likes: 156000,
    num_views: 3600000,
    videoUrl: V(0),
    thumbnail: U("1494790108377-be9c29b29330"),
    textOverlay: "It wasn't one big moment. It was a thousand tiny ones.\n\nIt was the Sunday scaries starting on Friday night. It was crying in the bathroom between meetings. It was realizing I hadn't laughed — genuinely laughed — in weeks.\n\nIt was my doctor asking 'are you under stress?' and me saying 'no more than normal' while my blood pressure was through the roof.\n\nIt was my kid asking 'why are you always tired?' and not having an answer that made sense.\n\nThe day I quit, nothing dramatic happened. I just woke up and thought: 'I have one life. ONE. And I'm spending 10 hours a day making someone else rich while my health deteriorates.'\n\nThat was 2 years ago. I make less money now. But I sleep 8 hours, I pick my kids up from school, and I haven't had a panic attack since.\n\nNot everyone can quit their job. But everyone can start planning their exit.",
  },
  {
    id: 54,
    caption: "spiritual practices that actually changed my life (not just trendy ones)",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["Spirituality", "Self Improvement"],
    num_likes: 89000,
    num_views: 2100000,
    videoUrl: V(1),
    thumbnail: U("1542206395-9feb3edaa68d"),
    textOverlay: "I tried every spiritual practice that was trending. Manifestation journals, crystal healing, sound baths, moon rituals. Most of them did nothing. Here's what actually shifted something:\n\nMeditation — but not the pretty Instagram kind. The boring, sit-with-your-thoughts, want-to-quit-after-2-minutes kind. Consistency over perfection.\n\nGratitude — not listing random things. Deeply FEELING grateful for one specific thing each morning. Really sitting in it.\n\nSolitude — turning off my phone and being alone with myself for an hour. We're so afraid of silence that we never hear our own wisdom.\n\nService — doing something for someone else with zero expectation of return. This one rewired my brain faster than anything.\n\nSpiritual growth isn't about crystals and sage. It's about getting honest with yourself and doing the uncomfortable work.",
  },
  {
    id: 55,
    caption: "the email template that got me meetings with 12 CEOs",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["B2B SaaS/Platform", "Personal Brand"],
    num_likes: 112000,
    num_views: 2700000,
    videoUrl: V(2),
    thumbnail: U("1507003211169-0a1dd7228f2d"),
    textOverlay: "I cold-emailed 50 CEOs and got meetings with 12 of them. That's a 24% response rate when the industry average is 1-3%. Here's the exact template:\n\nSubject line: [Their company] + [specific observation]\n\nBody: 2 sentences max. Sentence 1: A genuine, specific compliment about something they recently did or said. Sentence 2: One line about how I could help with a specific problem.\n\nCTA: 'Would a 15-min call next week make sense?'\n\nThat's IT. No fluff. No 'I hope this email finds you well.' No attachments. No walls of text.\n\nWhy it works: CEOs get 200+ emails a day. They scan for 3 things: Is this relevant? Is it short? Is there a clear ask? Hit all 3 and you're in.\n\nThe key nobody tells you: research each person for 10 minutes before writing. That personalization is what separates a 1% response rate from a 24% one.",
  },
  {
    id: 56,
    caption: "as someone who lost 80lbs, here's what diet culture gets wrong",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["Health", "Fitness", "Self Improvement"],
    num_likes: 287000,
    num_views: 5900000,
    videoUrl: V(3),
    thumbnail: U("1571019614242-c5c5dee9f50b"),
    textOverlay: "I've lost 80 lbs and kept it off for 3 years. Here's everything diet culture got wrong:\n\n'Eat clean.' This is meaningless. There are no clean or dirty foods. There's food that nourishes and food that doesn't, and both have a place in your life.\n\n'No carbs after 6pm.' Your body doesn't have a carb curfew. Total calories matter. Timing barely matters.\n\n'Detox juices.' Your liver and kidneys are the detox. A $12 green juice is just expensive sugar water.\n\n'Cheat meals.' This language frames food as moral. You're not 'cheating.' You're eating pizza. It's fine.\n\nWhat actually worked: A moderate calorie deficit I could sustain for MONTHS. Walking 10k steps daily. Protein at every meal. Sleeping 7+ hours. And therapy — because most of my overeating was emotional, not physical.\n\nThe best diet is the one you don't have to recover from.",
  },
  {
    id: 57,
    caption: "how I automated my entire Shopify store and went on vacation for 3 weeks",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["E-Commerce", "B2B SaaS/Platform", "Productivity"],
    num_likes: 98000,
    num_views: 2300000,
    videoUrl: V(4),
    thumbnail: U("1551434678-e076c223a692"),
    textOverlay: "Last month I went to Thailand for 3 weeks. My Shopify store did $34k while I was gone. Here's the automation stack:\n\nFulfillment: Everything ships through a 3PL. Orders auto-forward, they pick, pack, and ship within 24 hours.\n\nCustomer service: 80% of questions are answered by my FAQ chatbot. The other 20% go to my VA in the Philippines ($800/month, absolute rockstar).\n\nAds: I set up 3 evergreen ad campaigns with auto-scaling rules. If ROAS drops below 2.5x, it pauses automatically.\n\nEmail flows: Welcome series, abandoned cart, post-purchase upsell, win-back. All automated. These alone generate $8k/month.\n\nInventory: Auto-reorder triggers when stock hits 50 units.\n\nTotal time to set all this up: about 3 months. But now the business runs with 5 hours/week of my time. That's the real flex.",
  },
  {
    id: 58,
    caption: "things my therapist taught me about setting boundaries",
    subCaption: null,
    contentType: "wall-of-text",
    tags: ["Health", "Relationships", "Self Improvement"],
    num_likes: 245000,
    num_views: 5400000,
    videoUrl: V(5),
    thumbnail: U("1494790108377-be9c29b29330"),
    textOverlay: "My therapist said: 'Boundaries aren't walls. They're gates. You decide who gets in and when.'\n\nThat changed everything for me. I used to think setting boundaries meant being mean. It doesn't. It means being clear.\n\n'I can't take calls after 7pm' isn't rude. It's self-preservation.\n'I need a day to think about that' isn't weak. It's wise.\n'I love you but I can't help you with this' isn't selfish. It's honest.\n\nThe hardest boundary I ever set was with my own mother. I told her she couldn't comment on my weight anymore. She cried. I almost caved. But 6 months later, our relationship is better than it's been in 20 years.\n\nBoundaries feel terrible at first because we're used to people-pleasing. But the discomfort of setting a boundary lasts a moment. The resentment of not setting one lasts years.",
  },

  // ====================  VIDEO HOOK & DEMO (59–78)  ====================
  {
    id: 59,
    caption: "6 Truths About Your Home That No One Tells You",
    subCaption: null,
    contentType: "video-hook",
    tags: ["Course/Digital Product", "Self Improvement", "B2C App"],
    num_likes: 13000,
    num_views: 220000,
    videoUrl: V(7),
    thumbnail: U("1524504388940-b1c1722653e1"),
    hookText: "Stop scrolling. Your home is literally making you anxious and you don't even realize it.",
    demoText: "Clutter raises cortisol by 30%. Your bedroom lighting is disrupting your sleep. And that air freshener? It's pumping endocrine disruptors into every room. Here are 6 truths about your home environment that nobody talks about...",
  },
  {
    id: 60,
    caption: "My therapist said something that completely broke me",
    subCaption: null,
    contentType: "video-hook",
    tags: ["B2C App", "Health"],
    num_likes: 40200,
    num_views: 1000000,
    videoUrl: V(0),
    thumbnail: U("1573496359142-b8d87734a5a2"),
    hookText: "My therapist said something last week that completely broke me in the best way possible.",
    demoText: "She said: 'You don't need other people to validate your feelings. The fact that you FEEL it is validation enough.' I've spent my entire life waiting for someone to tell me my emotions were okay. Turns out, I was the only permission I ever needed.",
  },
  {
    id: 61,
    caption: "I got rejected from 200 jobs before I realized the real problem",
    subCaption: "spoiler: the resume insights are next-level accurate",
    contentType: "video-hook",
    tags: ["B2B App", "B2B SaaS/Platform"],
    num_likes: 8500,
    num_views: 261000,
    videoUrl: V(1),
    thumbnail: U("1560250097-0b93528c311a"),
    hookText: "I got rejected from 200 jobs before I realized the problem wasn't me — it was my resume format.",
    demoText: "So I built an AI tool that scans your resume against the actual job description and tells you EXACTLY what to fix. It checks keyword matching, formatting issues, and even predicts your interview chances. Watch me scan this resume live...",
  },
  {
    id: 62,
    caption: "medicine tips for a better life",
    subCaption: null,
    contentType: "video-hook",
    tags: ["Health", "B2C App"],
    num_likes: 8200,
    num_views: 164200,
    videoUrl: V(2),
    thumbnail: U("1534528741775-53994a69daeb"),
    hookText: "Your pharmacist knows things your doctor won't tell you. Here's the truth about common medications.",
    demoText: "Taking ibuprofen on an empty stomach? You're destroying your gut lining. Using melatonin every night? You're downregulating your natural production. Mixing certain supplements with prescriptions? Could be dangerous. Here are the medicine tips that actually improve your health...",
  },
  {
    id: 63,
    caption: "POV: you just discovered this skincare routine",
    subCaption: null,
    contentType: "video-hook",
    tags: ["Beauty", "B2C App"],
    num_likes: 156000,
    num_views: 3700000,
    videoUrl: V(3),
    thumbnail: U("1531746020798-e6953c6e8e04"),
    hookText: "A dermatologist told me that 90% of people do their skincare in the WRONG order.",
    demoText: "Cleanser, toner, serum, moisturizer, SPF. That's it. Stop layering 12 products. Your skin barrier can only absorb so much. And that expensive retinol? If you're using it before your vitamin C, you're canceling both out. Let me show you the correct order...",
  },
  {
    id: 64,
    caption: "watch me build a SaaS in 24 hours using AI",
    subCaption: null,
    contentType: "video-hook",
    tags: ["B2B SaaS/Platform", "Productivity"],
    num_likes: 88000,
    num_views: 2000000,
    videoUrl: V(4),
    thumbnail: U("1560250097-0b93528c311a"),
    hookText: "I just built a complete SaaS product in 24 hours with zero coding experience.",
    demoText: "Hour 1-4: Used Claude to architect the entire backend. Hour 5-10: Built the frontend with v0 by Vercel. Hour 11-16: Integrated Stripe payments and auth. Hour 17-20: Deployed and set up a domain. Hour 21-24: Posted on Twitter, got 3 paying users at $29/month. Total cost: $0.",
  },
  {
    id: 65,
    caption: "the morning routine that fixed my anxiety",
    subCaption: null,
    contentType: "video-hook",
    tags: ["Health", "Self Improvement"],
    num_likes: 267000,
    num_views: 6000000,
    videoUrl: V(5),
    thumbnail: U("1517841905240-472988babdf9"),
    hookText: "I used to wake up with my heart racing every single morning. Then I changed ONE thing.",
    demoText: "I stopped checking my phone for the first 60 minutes after waking up. No email. No social media. No news. Instead: sunlight in my eyes within 10 minutes, a glass of water, and 5 minutes of deep breathing. Within 2 weeks, the morning anxiety was gone.",
  },
  {
    id: 66,
    caption: "how this app is making teens $500/week",
    subCaption: null,
    contentType: "video-hook",
    tags: ["B2C App", "Finance"],
    num_likes: 134000,
    num_views: 3100000,
    videoUrl: V(6),
    thumbnail: U("1507003211169-0a1dd7228f2d"),
    hookText: "A 17-year-old just showed me his phone and he's making $500 a week with an app I'd never heard of.",
    demoText: "It's called TaskRabbit and teens are using it to do simple tasks in their neighborhood — assembling furniture, running errands, helping with moves. This kid does 2 hours after school and all day Saturday. That's $2k/month at 17.",
  },
  {
    id: 67,
    caption: "reacting to my first ever TikTok vs now",
    subCaption: null,
    contentType: "video-hook",
    tags: ["Personal Brand", "B2C App"],
    num_likes: 189000,
    num_views: 4300000,
    videoUrl: V(7),
    thumbnail: U("1580489944761-15a19d654956"),
    hookText: "I just found my first ever TikTok from 2021 and I'm genuinely embarrassed.",
    demoText: "Bad lighting. No hook. Talking to the camera like I'm leaving a voicemail. 43 views. Compare it to today: cinematic lighting, pattern interrupts every 3 seconds, and strategic hooks. The difference? 400 videos of practice. Nobody starts good.",
  },
  {
    id: 68,
    caption: "day in the life of a solo founder making $30k/mo",
    subCaption: null,
    contentType: "video-hook",
    tags: ["B2B App", "Personal Brand"],
    num_likes: 95000,
    num_views: 2200000,
    videoUrl: V(0),
    thumbnail: U("1506794778202-cad84cf45f1d"),
    hookText: "People think making $30k/month means I work 16-hour days. Here's what my day actually looks like.",
    demoText: "7am: Wake up, no alarm. 8am: Coffee + review metrics for 15 min. 9am-12pm: Deep work on the product. 12pm: Gym. 2:30-4pm: Customer calls + support. 4pm: Done. The secret? I automated everything else. 6 tools run the business while I sleep.",
  },
  {
    id: 69,
    caption: "the product demo that made investors fight over us",
    subCaption: null,
    contentType: "video-hook",
    tags: ["B2B SaaS/Platform", "B2B App"],
    num_likes: 72000,
    num_views: 1900000,
    videoUrl: V(1),
    thumbnail: U("1500648767791-00dcc994a43e"),
    hookText: "We showed this demo to 5 VCs. 3 of them sent term sheets within 48 hours.",
    demoText: "The product takes your messy customer data and creates a real-time dashboard in under 60 seconds. No code. No CSV uploads. Just connect your Stripe, and boom — churn prediction, revenue forecasting, and cohort analysis. Watch me set it up from scratch...",
  },
  {
    id: 70,
    caption: "this breathing technique stopped my panic attacks",
    subCaption: null,
    contentType: "video-hook",
    tags: ["Health", "Self Improvement"],
    num_likes: 345000,
    num_views: 5800000,
    videoUrl: V(2),
    thumbnail: U("1573496359142-b8d87734a5a2"),
    hookText: "I had panic attacks for 3 years. This 90-second technique stopped them completely.",
    demoText: "It's called physiological sighing. Two short inhales through the nose, then one long exhale through the mouth. It activates your parasympathetic nervous system instantly. Stanford proved it's the fastest way to calm down in real-time. Do it with me right now...",
  },
  {
    id: 71,
    caption: "I replaced all my meals with this for 30 days",
    subCaption: null,
    contentType: "video-hook",
    tags: ["Health", "Supplement", "Fitness"],
    num_likes: 198000,
    num_views: 4500000,
    videoUrl: V(3),
    thumbnail: U("1548690312-e3b507d8c110"),
    hookText: "I ate the same 4 meals every day for 30 days. My body fat dropped from 22% to 16%.",
    demoText: "Meal 1: Protein oats with banana and peanut butter. Meal 2: Chicken, rice, and broccoli. Meal 3: Salmon with sweet potato. Meal 4: Greek yogurt with berries. Total: 2,200 calories, 180g protein. The simplicity removed decision fatigue and I never felt deprived.",
  },
  {
    id: 72,
    caption: "the negotiation trick that doubled my salary",
    subCaption: null,
    contentType: "video-hook",
    tags: ["B2C App", "Finance", "Productivity"],
    num_likes: 156000,
    num_views: 3400000,
    videoUrl: V(4),
    thumbnail: U("1507003211169-0a1dd7228f2d"),
    hookText: "I asked for a $40K raise and got it. The trick? I never said a number first.",
    demoText: "Step 1: Document every win from the past year with dollar amounts attached. Step 2: Ask your manager what the top of the pay band is for your role. Step 3: Let them anchor first. Step 4: Counter 15% higher than your target. Step 5: Be willing to walk. The power shifts when they know you have options.",
  },
  {
    id: 73,
    caption: "how we grew our app to 50K users with $0 marketing budget",
    subCaption: null,
    contentType: "video-hook",
    tags: ["B2C App", "B2B SaaS/Platform"],
    num_likes: 112000,
    num_views: 2600000,
    videoUrl: V(5),
    thumbnail: U("1560250097-0b93528c311a"),
    hookText: "We have 50,000 users and have spent exactly $0 on ads. Here's our entire growth playbook.",
    demoText: "Strategy 1: Built a free tool that solves 1 problem — it went viral on Twitter. Strategy 2: Every user gets a personalized onboarding email from me. Strategy 3: We incentivize referrals with premium features. Strategy 4: We post user success stories as content. Our CAC is literally $0.",
  },
  {
    id: 74,
    caption: "the 3-second rule that made me fearless at networking events",
    subCaption: null,
    contentType: "video-hook",
    tags: ["Personal Brand", "Self Improvement"],
    num_likes: 87000,
    num_views: 2000000,
    videoUrl: V(6),
    thumbnail: U("1506794778202-cad84cf45f1d"),
    hookText: "I used to be terrified of networking events. Then someone taught me the 3-second rule.",
    demoText: "When you see someone you want to talk to, you have 3 seconds to walk over and say something. After 3 seconds, your brain creates excuses. The trick: don't think about what to say. Just walk over, extend your hand, and say 'Hey, I don't think we've met yet.' That's it. The conversation takes care of itself.",
  },
  {
    id: 75,
    caption: "this Notion setup replaced 6 apps for my business",
    subCaption: null,
    contentType: "video-hook",
    tags: ["B2B SaaS/Platform", "Productivity"],
    num_likes: 67000,
    num_views: 1800000,
    videoUrl: V(7),
    thumbnail: U("1519389950473-47ba0277781c"),
    hookText: "I was paying $340/month for 6 different SaaS tools. Now I pay $8 for Notion.",
    demoText: "Replaced: Trello for project management. Airtable for CRM. Google Sheets for finances. Calendly for scheduling. Confluence for docs. And Todoist for tasks. I built a single Notion workspace that does ALL of it. Let me show you the setup...",
  },
  {
    id: 76,
    caption: "what 10 years of weightlifting taught me about life",
    subCaption: null,
    contentType: "video-hook",
    tags: ["Fitness", "Self Improvement"],
    num_likes: 178000,
    num_views: 3900000,
    videoUrl: V(0),
    thumbnail: U("1548690312-e3b507d8c110"),
    hookText: "10 years of lifting weights taught me more about life than any book ever did.",
    demoText: "Lesson 1: Consistency beats intensity. The person who shows up 4x/week for 10 years beats the person who goes hard for 2 months. Lesson 2: Progressive overload. If you're not uncomfortable, you're not growing. Lesson 3: Rest is not weakness. Recovery is where growth happens. Lesson 4: You're never done. There is no finish line.",
  },
  {
    id: 77,
    caption: "I tested every AI writing tool so you don't have to",
    subCaption: null,
    contentType: "video-hook",
    tags: ["B2B SaaS/Platform", "Productivity"],
    num_likes: 94000,
    num_views: 2100000,
    videoUrl: V(1),
    thumbnail: U("1553877522-43269d4ea984"),
    hookText: "I spent $500 testing every AI writing tool on the market. Only 2 are worth your money.",
    demoText: "I tested ChatGPT, Claude, Jasper, Copy.ai, Writesonic, Rytr, and 6 others. Gave them all the same prompts: sales copy, blog posts, emails, and social media captions. The results were shocking. Most of them produce generic slop. But two of them consistently wrote content that was indistinguishable from human-written. Here's the head-to-head comparison...",
  },
  {
    id: 78,
    caption: "the gym hack that's adding 20lbs to all my lifts",
    subCaption: null,
    contentType: "video-hook",
    tags: ["Fitness", "Health"],
    num_likes: 134000,
    num_views: 3200000,
    videoUrl: V(2),
    thumbnail: U("1552374196-c4e7ffc6e126"),
    hookText: "I added 20lbs to my bench press in 4 weeks by changing ONE thing about my warm-up.",
    demoText: "Instead of just doing light sets, I started doing CNS activation: 3 explosive clap push-ups before my working sets. It fires up your central nervous system and recruits more motor units. It's like turning on all the engines before takeoff. Watch my working set before and after — the bar speed difference is insane.",
  },

  // ====================  GREEN SCREEN MEME (79–105)  ====================
  {
    id: 79,
    caption: "habits that helped me feel way less bloated",
    subCaption: null,
    contentType: "green-screen",
    tags: ["E-Commerce", "Supplement"],
    num_likes: 46200,
    num_views: 1000000,
    videoUrl: V(2),
    thumbnail: U("1557862921-37829c790f19"),
    topText: "habits that helped me feel way less bloated",
    bottomText: "1. Apple cider vinegar before meals\n2. Digestive enzymes with every meal\n3. Stop drinking water DURING meals\n4. Walk 10 min after eating\n5. Cut dairy for 2 weeks and see what happens",
  },
  {
    id: 80,
    caption: "POV: you're at the gym on Valentine's Day and your crush isn't there",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Fitness", "B2C App"],
    num_likes: 156000,
    num_views: 4200000,
    videoUrl: V(3),
    thumbnail: U("1596386461350-326155643bfa"),
    topText: "POV: you're at the gym on February 14th",
    bottomText: "and your gym crush isn't there because they actually have a valentine...\n\n*proceeds to do angry deadlifts*\n\nAt least the barbell will never leave me",
  },
  {
    id: 81,
    caption: "when your crush asks what you do for a living and you're a content creator",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Personal Brand", "B2C App"],
    num_likes: 278000,
    num_views: 6800000,
    videoUrl: V(4),
    thumbnail: U("1531427186611-ecfd6d936c79"),
    topText: "when your crush asks what you do for a living",
    bottomText: "Me: I'm in digital media and brand partnerships\n\nWhat I actually do: talk to my phone in my bedroom for 4 hours and hope the algorithm blesses me\n\nThem: oh so like... YouTube?\nMe: *dies inside*",
  },
  {
    id: 82,
    caption: "low-key regret making this trip to japan...",
    subCaption: null,
    contentType: "green-screen",
    tags: ["B2C App", "Self Improvement"],
    num_likes: 89300,
    num_views: 2800000,
    videoUrl: V(5),
    thumbnail: U("1573497019940-1c28c88b4f3e"),
    topText: "low-key regret making this trip to japan...",
    bottomText: "because now every other country feels mid.\n\nThe food? Immaculate.\nThe people? Kindest humans alive.\nThe trains? On time to the SECOND.\nThe cleanliness? You could eat off the subway floor.\n\nI'm ruined for travel forever.",
  },
  {
    id: 83,
    caption: "hacks to stop procrastinating (stop doing this to your future self)",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Productivity", "Self Improvement"],
    num_likes: 192000,
    num_views: 1350000,
    videoUrl: V(6),
    thumbnail: U("1574279606264-2f5d3fb6a4b5"),
    topText: "hacks to stop procrastinating",
    bottomText: "1. The 2-minute rule: if it takes less than 2 min, do it NOW\n2. Body doubling: work next to someone (even on FaceTime)\n3. Eat the frog: do the hardest task FIRST\n4. Remove friction: prep everything the night before\n5. Stop telling yourself you'll 'do it later' — later never comes",
  },
  {
    id: 84,
    caption: "POV: the gym at 5am vs 5pm",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Fitness", "B2C App"],
    num_likes: 312000,
    num_views: 5900000,
    videoUrl: V(7),
    thumbnail: U("1596386461350-326155643bfa"),
    topText: "the gym at 5am vs 5pm",
    bottomText: "5am: Empty. Peaceful. Everyone minds their business. Nodding respectfully at each other like soldiers.\n\n5pm: A warzone. Every bench taken. Someone curling in the squat rack. A guy doing a TikTok dance between sets.\n\nChoose your fighter.",
  },
  {
    id: 85,
    caption: "me explaining crypto to my parents at thanksgiving",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Finance", "B2C App"],
    num_likes: 245000,
    num_views: 5900000,
    videoUrl: V(0),
    thumbnail: U("1531427186611-ecfd6d936c79"),
    topText: "me explaining crypto to my parents at thanksgiving",
    bottomText: "Me: so basically it's digital money secured by math\nDad: so it's not real money?\nMe: well it IS real it's just—\nMom: can you hold it?\nMe: no but—\nDad: so it's fake money\nMe: *stares at turkey*\nMom: sweetie maybe just put it in a savings account",
  },
  {
    id: 86,
    caption: "when the client says 'can you make the logo bigger'",
    subCaption: null,
    contentType: "green-screen",
    tags: ["B2B App", "B2B SaaS/Platform"],
    num_likes: 167000,
    num_views: 4000000,
    videoUrl: V(1),
    thumbnail: U("1551836022-4b4d0dbfbd21"),
    topText: "client feedback throughout a design project",
    bottomText: "Revision 1: 'Can you make the logo bigger?'\nRevision 2: 'Can you try it in blue? And red. And green.'\nRevision 3: 'My wife doesn't like it'\nRevision 4: 'Actually can we go back to the first version?'\nRevision 5: 'Can you just make it pop more?'\nMe: *opens LinkedIn, starts job hunting*",
  },
  {
    id: 87,
    caption: "the face I make when someone says 'just be yourself'",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Self Improvement", "B2C App"],
    num_likes: 198000,
    num_views: 4700000,
    videoUrl: V(2),
    thumbnail: U("1557862921-37829c790f19"),
    topText: "the face I make when someone says 'just be yourself'",
    bottomText: "Sir/ma'am, WHICH self?\n\nThe work self? The home self? The 'talking to my therapist' self? The '3am overthinking' self? The 'social media' self? The 'grocery store at 10pm in sweatpants' self?\n\nPlease be more specific.",
  },
  {
    id: 88,
    caption: "me after my 3rd failed diet this year",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Health", "Fitness"],
    num_likes: 223000,
    num_views: 5400000,
    videoUrl: V(3),
    thumbnail: U("1596386461350-326155643bfa"),
    topText: "me after my 3rd failed diet this year",
    bottomText: "January: keto. Lasted 9 days.\nMarch: intermittent fasting. Broke at 11am on day 2.\nMay: carnivore diet. Ate a piece of bread by dinner.\n\nPlot twist: the diet that finally worked was just eating normal food in normal amounts and going for walks. Revolutionary, I know.",
  },
  {
    id: 89,
    caption: "when you realize you've been doom scrolling for 2 hours",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Productivity", "Self Improvement"],
    num_likes: 287000,
    num_views: 6900000,
    videoUrl: V(4),
    thumbnail: U("1574279606264-2f5d3fb6a4b5"),
    topText: "the 5 stages of doom scrolling",
    bottomText: "Stage 1: 'I'll just check for 5 minutes'\nStage 2: 'Okay ONE more video'\nStage 3: 'Wait how did I get to this side of the internet'\nStage 4: *checks time* 'IT'S BEEN 2 HOURS?!'\nStage 5: 'I'll start being productive... after this next one'\n\n*repeat daily*",
  },
  {
    id: 90,
    caption: "POV: your startup just got its first paying customer",
    subCaption: null,
    contentType: "green-screen",
    tags: ["B2B App", "B2B SaaS/Platform"],
    num_likes: 145000,
    num_views: 3500000,
    videoUrl: V(5),
    thumbnail: U("1521791136064-7986c2920216"),
    topText: "POV: your startup just got its first paying customer",
    bottomText: "The notification: 'You received $29.00'\n\nMe externally: *professional nod* 'The business model is validated.'\n\nMe internally: *SCREAMING* *CRYING* *CALLING MY MOM* *UPDATING LINKEDIN BIO TO CEO* *PLANNING IPO*\n\nThat $29 hit different when you've been at $0 for 6 months.",
  },
  {
    id: 91,
    caption: "me trying to explain what I do in tech to my grandma",
    subCaption: null,
    contentType: "green-screen",
    tags: ["B2B SaaS/Platform", "Personal Brand"],
    num_likes: 198000,
    num_views: 4800000,
    videoUrl: V(6),
    thumbnail: U("1573497019940-1c28c88b4f3e"),
    topText: "me trying to explain what I do in tech to my grandma",
    bottomText: "Me: I build software\nGrandma: like Microsoft?\nMe: no it's a SaaS platform that—\nGrandma: so you work for Bill Gates?\nMe: no grandma I—\nGrandma: can you fix my printer?\nMe: that's not... yes grandma I'll fix your printer",
  },
  {
    id: 92,
    caption: "POV: your client asks for 'just one small change'",
    subCaption: null,
    contentType: "green-screen",
    tags: ["B2B App", "B2B SaaS/Platform"],
    num_likes: 234000,
    num_views: 5600000,
    videoUrl: V(7),
    thumbnail: U("1531427186611-ecfd6d936c79"),
    topText: "POV: your client asks for 'just one small change'",
    bottomText: "'Just one small change' = rewrite the entire backend\n'Can we try something different?' = start over from scratch\n'I'll know what I want when I see it' = infinite revisions\n'Let's circle back' = I'm not paying for this phase\n'We need it yesterday' = I forgot to tell you about this for 3 weeks",
  },
  {
    id: 93,
    caption: "things that are socially acceptable but actually insane",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Self Improvement", "B2C App"],
    num_likes: 356000,
    num_views: 6200000,
    videoUrl: V(0),
    thumbnail: U("1557862921-37829c790f19"),
    topText: "things that are socially acceptable but actually insane",
    bottomText: "Working 40+ hours/week at a job you hate\nSpending 2 hours commuting daily to sit in a cubicle\nTaking on $200k debt at 18 for a degree you're unsure about\nDrinking caffeine to function and alcohol to relax\nRetiring at 65 and calling the last years 'the golden years'\n\nWe normalized all of this?",
  },
  {
    id: 94,
    caption: "the stages of starting a side hustle",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Course/Digital Product", "Personal Brand"],
    num_likes: 189000,
    num_views: 4400000,
    videoUrl: V(1),
    thumbnail: U("1551836022-4b4d0dbfbd21"),
    topText: "the stages of starting a side hustle",
    bottomText: "Week 1: THIS IS THE BEST IDEA EVER\nWeek 2: building building building so excited\nWeek 3: wait this is harder than I thought\nWeek 4: maybe I should pivot\nWeek 5: *googles 'is it too late to go back to my job'*\nWeek 6: gets first sale for $9\nWeek 6: I'M BASICALLY ELON MUSK",
  },
  {
    id: 95,
    caption: "dating app convos in 2026 be like",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Relationships", "B2C App"],
    num_likes: 278000,
    num_views: 5900000,
    videoUrl: V(2),
    thumbnail: U("1573497019940-1c28c88b4f3e"),
    topText: "dating app convos in 2026 be like",
    bottomText: "Them: hey\nMe: hey!\nThem: how are you\nMe: good, you?\nThem: good\n\n*3 days of silence*\n\nThem: so what are you looking for?\nMe: something real and genuine\nThem: same\n\n*never speaks again*\n\nThe bar is underground and we're still tripping over it.",
  },
  {
    id: 96,
    caption: "me looking at my bank account after 'treating myself'",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Finance", "Self Improvement"],
    num_likes: 312000,
    num_views: 6800000,
    videoUrl: V(3),
    thumbnail: U("1596386461350-326155643bfa"),
    topText: "me looking at my bank account after 'treating myself'",
    bottomText: "Monday: 'I deserve this coffee' ($7)\nTuesday: 'I deserve this lunch out' ($24)\nWednesday: 'I deserve this Amazon order' ($89)\nThursday: 'I deserve this—'\nBank account: you deserve financial literacy\n\nI don't have a spending problem I have a deserving problem",
  },
  {
    id: 97,
    caption: "how introverts recharge vs how extroverts think we recharge",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Self Improvement", "B2C App"],
    num_likes: 245000,
    num_views: 5200000,
    videoUrl: V(4),
    thumbnail: U("1574279606264-2f5d3fb6a4b5"),
    topText: "how introverts recharge vs how extroverts think we recharge",
    bottomText: "How extroverts think we recharge:\n- sitting alone crying\n- staring at a wall\n- being depressed\n\nHow we actually recharge:\n- a book and a candle\n- cooking with a podcast on\n- a solo walk with headphones\n- scrolling in peace\n- literally just SILENCE\n\nWe're not sad. We're RESTORING.",
  },
  {
    id: 98,
    caption: "things my boss said that actually changed my career",
    subCaption: null,
    contentType: "green-screen",
    tags: ["B2B App", "Productivity"],
    num_likes: 167000,
    num_views: 3900000,
    videoUrl: V(5),
    thumbnail: U("1508341591423-4347099e1f19"),
    topText: "things my boss said that actually changed my career",
    bottomText: "'Stop asking for permission and start asking for forgiveness.'\n'Your job is to make me look good. My job is to make you look good.'\n'If you're the smartest person in the room, you're in the wrong room.'\n'Under-promise and over-deliver. Every. Single. Time.'\n'The promotion won't change your life. The skills will.'",
  },
  {
    id: 99,
    caption: "when someone says 'we should catch up soon' but neither of you texts first",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Relationships", "B2C App"],
    num_likes: 289000,
    num_views: 6100000,
    videoUrl: V(6),
    thumbnail: U("1557862921-37829c790f19"),
    topText: "when someone says 'we should catch up soon'",
    bottomText: "Both of you: *aggressively doesn't text first*\n\n6 months later...\n\n'OMG HI STRANGER!!! It's been SO long!!'\n'We HAVE to get together soon!!'\n'Absolutely!! Name a day!!'\n\n*both proceed to not name a day*\n\nSee you in another 6 months bestie",
  },
  {
    id: 100,
    caption: "the financial advice I'd give my 18-year-old self",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Finance", "Self Improvement"],
    num_likes: 203000,
    num_views: 4800000,
    videoUrl: V(7),
    thumbnail: U("1507679799987-c73779587ccf"),
    topText: "the financial advice I'd give my 18-year-old self",
    bottomText: "1. Open a Roth IRA IMMEDIATELY\n2. Every raise → increase savings, not lifestyle\n3. Credit cards are tools, not free money\n4. $100/month invested at 18 = $1M+ by 65\n5. Your car should not cost more than 3 months salary\n6. NEVER cosign a loan for anyone\n7. The person selling you financial freedom is selling you a course",
  },
  {
    id: 101,
    caption: "how my morning routine evolved from 20 to 30",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Self Improvement", "Health"],
    num_likes: 178000,
    num_views: 4100000,
    videoUrl: V(0),
    thumbnail: U("1573164713988-8665fc963095"),
    topText: "how my morning routine evolved from 20 to 30",
    bottomText: "Age 20: wake up 15 min before class, grab a Monster, sprint\nAge 23: wake up at 8, scroll phone for 40 min, panic\nAge 25: alarm at 6, snooze until 7:30, coffee, chaos\nAge 28: 6:30am, gym, cold shower, green juice (insufferable era)\nAge 30: 7am, coffee in silence, walk, start work at 9\n\nTurns out the best routine is the boring one.",
  },
  {
    id: 102,
    caption: "red flags in online courses disguised as 'opportunities'",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Course/Digital Product", "E-Commerce"],
    num_likes: 234000,
    num_views: 5500000,
    videoUrl: V(1),
    thumbnail: U("1531427186611-ecfd6d936c79"),
    topText: "red flags in online courses",
    bottomText: "'I made $100K in 30 days and YOU can too'\n*course costs $997*\n*testimonials are all screenshots with no verification*\n*guru lives in rented Airbnb for photos*\n*'limited spots available' but it's been 'limited' for 6 months*\n*the only skill taught is selling the same course*\n\nThe pyramid has wifi now.",
  },
  {
    id: 103,
    caption: "POV: you work in marketing and your family asks what you do",
    subCaption: null,
    contentType: "green-screen",
    tags: ["B2B App", "Personal Brand"],
    num_likes: 156000,
    num_views: 3700000,
    videoUrl: V(2),
    thumbnail: U("1551836022-4b4d0dbfbd21"),
    topText: "when your family asks what you do in marketing",
    bottomText: "Uncle: so you make commercials?\nMe: no I do growth marketing for a—\nMom: he does stuff on the computer\nDad: can you sell my friend's restaurant?\nCousin: can you make me go viral?\nGrandma: so you're in advertising like Mad Men?\nMe: ...yes grandma. Exactly like Mad Men.",
  },
  {
    id: 104,
    caption: "signs you're the 'therapist friend' and need to set boundaries",
    subCaption: null,
    contentType: "green-screen",
    tags: ["Health", "Relationships", "Self Improvement"],
    num_likes: 267000,
    num_views: 5800000,
    videoUrl: V(3),
    thumbnail: U("1557862921-37829c790f19"),
    topText: "signs you're the 'therapist friend'",
    bottomText: "Everyone comes to you with their problems but never asks how YOU are\n\nYou know everyone's trauma like it's a Netflix series\n\nYou give advice you should probably take yourself\n\nYou're emotionally exhausted after every hangout\n\nYou've said 'I'm fine' 4,000 times this week and meant it 0 times\n\nBabes you need a therapist FOR being the therapist friend",
  },
  {
    id: 105,
    caption: "when your e-commerce store gets its first 1-star review",
    subCaption: null,
    contentType: "green-screen",
    tags: ["E-Commerce", "B2C App"],
    num_likes: 145000,
    num_views: 3400000,
    videoUrl: V(4),
    thumbnail: U("1596386461350-326155643bfa"),
    topText: "stages of receiving your first 1-star review",
    bottomText: "Stage 1: DENIAL — 'they must have the wrong product'\nStage 2: ANGER — 'I PUT MY HEART INTO THIS'\nStage 3: BARGAINING — 'maybe I can offer them a refund and they'll update it?'\nStage 4: DEPRESSION — *stares at ceiling for 2 hours*\nStage 5: ACCEPTANCE — 'every great brand has haters, this means I've made it'\n\nStage 6: screenshots it for content",
  },
];

// ============================================================
// ALL TAGS (exact labels and colors from the original SaaS)
// ============================================================
export const CONTENT_TAGS = [
  { label: "B2B App",               color: "#DBEAFE", textColor: "#1D4ED8" },
  { label: "B2B SaaS/Platform",     color: "#FEF9C3", textColor: "#92400E" },
  { label: "B2C App",               color: "#DCFCE7", textColor: "#15803D" },
  { label: "E-Commerce",            color: "#FEE2E2", textColor: "#B91C1C" },
  { label: "Self Improvement",      color: "#EDE9FE", textColor: "#6D28D9" },
  { label: "Productivity",          color: "#E0F2FE", textColor: "#0369A1" },
  { label: "Fitness",               color: "#FCE7F3", textColor: "#9D174D" },
  { label: "Beauty",                color: "#FFF7ED", textColor: "#C2410C" },
  { label: "Course/Digital Product", color: "#F0FDF4", textColor: "#166534" },
  { label: "Personal Brand",        color: "#FEF3C7", textColor: "#B45309" },
  { label: "Spirituality",          color: "#FAE8FF", textColor: "#7E22CE" },
  { label: "Health",                color: "#ECFDF5", textColor: "#065F46" },
  { label: "Supplement",            color: "#F0FFF4", textColor: "#14532D" },
  { label: "Finance",               color: "#FEF3C7", textColor: "#92400E" },
  { label: "Relationships",         color: "#FDE8E8", textColor: "#9B1C1C" },
  { label: "Reaction",              color: "#E5EDFF", textColor: "#3730A3" },
  { label: "Woman",                 color: "#FDF2F8", textColor: "#831843" },
  { label: "Man",                   color: "#EFF6FF", textColor: "#1E3A5F" },
];

// Helper: get content filtered by type
export const getByType = (type) => {
  const map = {
    slideshow: "slideshow",
    "wall-of-text": "wall-of-text",
    walloftext: "wall-of-text",
    "video-hook": "video-hook",
    videohook: "video-hook",
    "green-screen": "green-screen",
    greenscreen: "green-screen",
  };
  const t = map[type] || type;
  return VIRAL_CONTENT.filter((v) => v.contentType === t);
};

// Helper: format big numbers like TikTok
export const fmtNum = (n) => {
  if (!n) return "0";
  if (n >= 1000000) return (n / 1000000).toFixed(1).replace(".0", "") + "M";
  if (n >= 1000) return (n / 1000).toFixed(1).replace(".0", "") + "K";
  return String(n);
};
